@startuml
!include ./Users/haler/Desktop/Faks/3-godina/PROGI/travel-tales-app/backend/Program.puml
!include ./Migrations/20241105224710_InitialCreate.Designer.puml
!include ./Migrations/20241112101358_UpdatingAspNetUsers.puml
!include ./Migrations/ApplicationDBContextModelSnapshot.puml
!include ./Migrations/20241112101358_UpdatingAspNetUsers.Designer.puml
!include ./Migrations/20241105224710_InitialCreate.puml
!include ./Repository/LocationRepository.puml
!include ./Repository/UserRepository.puml
!include ./Models/User.puml
!include ./Models/Location.puml
!include ./Mappers/LocationMappers.puml
!include ./Mappers/UserMappers.puml
!include ./Mappers/RoleMappers.puml
!include ./Service/TokenService.puml
!include ./Controllers/AccountController.puml
!include ./Controllers/UserController.puml
!include ./Controllers/LocationController.puml
!include ./Data/ApplicationDBContext.puml
!include ./Interfaces/ITokenService.puml
!include ./Interfaces/ILocationRepository.puml
!include ./Interfaces/IUserRepository.puml
!include ./Dtos/Location/CreateLocationRequestDto.puml
!include ./Dtos/Location/UpdateLocationRequestDto.puml
!include ./Dtos/User/UserDto.puml
!include ./Dtos/Account/RegisterDto.puml
!include ./Dtos/Account/UpdateDto.puml
!include ./Dtos/Account/LoginDto.puml
!include ./Dtos/Account/LogedInUserDto.puml
!include ./obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Debug/net8.0/backend.MvcApplicationPartsAssemblyInfo.puml
!include ./obj/Debug/net8.0/backend.GlobalUsings.g.puml
!include ./obj/Debug/net8.0/backend.AssemblyInfo.puml
!include ./obj/Release/net8.0/linux-arm64/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Release/net8.0/linux-arm64/backend.MvcApplicationPartsAssemblyInfo.puml
!include ./obj/Release/net8.0/linux-arm64/backend.GlobalUsings.g.puml
!include ./obj/Release/net8.0/linux-arm64/backend.AssemblyInfo.puml
!include ./obj/Release/net8.0/osx-arm64/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Release/net8.0/osx-arm64/backend.MvcApplicationPartsAssemblyInfo.puml
!include ./obj/Release/net8.0/osx-arm64/backend.GlobalUsings.g.puml
!include ./obj/Release/net8.0/osx-arm64/backend.AssemblyInfo.puml
!include ./obj/Release/net8.0/linux-x64/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Release/net8.0/linux-x64/backend.MvcApplicationPartsAssemblyInfo.puml
!include ./obj/Release/net8.0/linux-x64/backend.GlobalUsings.g.puml
!include ./obj/Release/net8.0/linux-x64/backend.AssemblyInfo.puml
!include ./obj/Debug/net8.0/linux-x64/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Debug/net8.0/linux-x64/backend.MvcApplicationPartsAssemblyInfo.puml
!include ./obj/Debug/net8.0/linux-x64/backend.GlobalUsings.g.puml
!include ./obj/Debug/net8.0/linux-x64/backend.AssemblyInfo.puml
@enduml
